"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Pantry = { id: string; name: string; approvedStatus: string };
type Membership = { userId: string; pantryId: string; pantryName: string; role: string };
export function AdminPantryControls({ pantries, memberships }: { pantries: Pantry[]; memberships: Membership[] }) {
  const router = useRouter(); const [error, setError] = useState<string | null>(null);
  async function update(pantryId: string, status: "approved" | "suspended") { setError(null); const response = await fetch("/api/marketplace/admin/pantries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: "status", pantryId, status }) }); const data = await response.json() as { error?: string }; if (!response.ok) setError(data.error ?? "Could not save."); else router.refresh(); }
  async function changeRole(membership: Membership, role: string) { setError(null); const response = await fetch("/api/marketplace/admin/pantries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: "role", pantryId: membership.pantryId, userId: membership.userId, role }) }); const data = await response.json() as { error?: string }; if (!response.ok) setError(data.error ?? "Could not save."); else router.refresh(); }
  return <><section className="mt-5"><h2 className="text-sm font-semibold">Pantries</h2><ul className="mt-2 divide-y divide-border">{pantries.map((pantry) => <li className="flex flex-wrap items-center justify-between gap-3 py-3" key={pantry.id}><p className="text-sm font-medium">{pantry.name}<span className="ml-2 text-muted">{pantry.approvedStatus}</span></p><div className="flex gap-2"><button className="min-h-11 rounded-panel border border-border px-3 text-sm font-semibold" onClick={() => update(pantry.id, "approved")} type="button">Approve</button><button className="min-h-11 rounded-panel border border-border px-3 text-sm font-semibold" onClick={() => update(pantry.id, "suspended")} type="button">Suspend</button></div></li>)}</ul></section><section className="mt-7"><h2 className="text-sm font-semibold">Members</h2><ul className="mt-2 divide-y divide-border">{memberships.map((membership) => <li className="flex flex-wrap items-center justify-between gap-3 py-3" key={`${membership.userId}-${membership.pantryId}`}><p className="text-sm"><span className="font-medium">{membership.pantryName}</span><span className="ml-2 font-mono text-xs text-muted">{membership.userId.slice(0, 8)}</span></p><select aria-label={`Role for ${membership.pantryName} member`} className="min-h-11 rounded-panel border border-border bg-surface px-3 text-sm" onChange={(event) => changeRole(membership, event.target.value)} value={membership.role}><option value="member">Member</option><option value="manager">Manager</option><option value="network_admin">Network admin</option></select></li>)}</ul>{error ? <p className="mt-2 text-sm text-danger">{error}</p> : null}</section></>;
}
